# Window configuration
[window]
# Set the window dimensions to 0 (full screen)
dimensions = { columns = 0, lines = 0 }

# Set the window padding
padding = { x = 10, y = 10 }

# Set the window startup mode to "Maximized"
startup_mode = "Maximized"

# Enable window decorations
decorations = "full"


# Font configuration
[font]
# Set the normal (regular) font
normal = { family = "Hack Nerd Font Mono", style = "Regular" }

# Set the bold font
bold = { family = "Hack Nerd Font Mono", style = "Bold" }

# Set the italic font
italic = { family = "Hack Nerd Font Mono", style = "Italic" }

# Set the font size
size = 10.0


# Cursor configuration
[cursor]
# Set the cursor style to "Block"
style = "Block"

# Enable unfocused hollow cursor
unfocused_hollow = true


# Selection configuration
[selection]
# Enable saving selected text to the clipboard
save_to_clipboard = true


# Shell configuration
[shell]
# Set the shell program to "/usr/local/bin/zsh"
program = "/usr/local/bin/zsh"

# Set the command-line arguments for the shell
args = ["--login"]


# Environment configuration
[env]
colorterm = "truecolor"
